import {
  AlertTriangle,
  Banknote,
  Briefcase,
  Building2,
  Car,
  CreditCard,
  Fuel,
  Gamepad2,
  GraduationCap,
  Gift,
  HeartPulse,
  Home,
  type LucideIcon,
  MoreHorizontal,
  Phone,
  PiggyBank,
  Repeat,
  Shirt,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Tag,
  TrendingUp,
  UtensilsCrossed,
  Wifi,
  Wrench,
} from "lucide-react";

const ICONS_POR_CATEGORIA: Record<string, LucideIcon> = {
  Moradia: Home,
  "Financiamento/Aluguel": Home,
  Condomínio: Building2,
  Carro: Car,
  "Manutenção Carro": Wrench,
  Seguro: ShieldCheck,
  Combustível: Fuel,
  Telefone: Phone,
  Internet: Wifi,
  Assinaturas: Repeat,
  Supermercado: ShoppingCart,
  Restaurante: UtensilsCrossed,
  Saúde: HeartPulse,
  Educação: GraduationCap,
  Lazer: Gamepad2,
  "Cuidados Pessoais": Sparkles,
  Vestuário: Shirt,
  Presentes: Gift,
  "Cartão de Crédito": CreditCard,
  Multas: AlertTriangle,
  Diversos: MoreHorizontal,
  Salário: Banknote,
  Prolabore: Briefcase,
  "Renda Extra": PiggyBank,
  Investimentos: TrendingUp,
};

export function getCategoryIcon(nome: string): LucideIcon {
  return ICONS_POR_CATEGORIA[nome] ?? Tag;
}
